# Base Image
FROM node:24-alpine

# Working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

RUN npm run build


# Command to run the app
CMD ["node", "dist/src/index.js"]